# Generated by Django 4.2.2 on 2023-06-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_rename_address_proposta_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='status',
        ),
    ]
