# Generated by Django 4.2.2 on 2023-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_remove_proposta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Reprovado', max_length=10),
        ),
    ]
